# compose version 3 is required for docker swarm
version: '3'

# services
services:

  site:
    image: site
    ports:
      - "5001:8080"
    deploy:
      replicas: 2

  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s